### ISSUE TITLE
NDS-controller-android-host

### ISSUE THREAD

**Issue by Buzbee** [Louisvh/cycle_consistent_INR#1]
Do you think you could update the source code for later versions of android for NDS-controller-android-host. There are outstanding issues with compiling it as is with the current android version.

**Comment by Louisvh** [comment]
Yeah, that project was all sorts of broken on modern Android versions; the Android API hasn't exactly been stable since whenever I originally wrote that thing. I just spent a few of hours to get it running again. The current version _should_ compile without a hitch. I've also added a pre-compiled apk if you just want to play with it for a bit.
